version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - ./public/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT

  adminer:
    image: adminer
    ports:
      - 8080:8080