version: '3.1'

services:
  db:
    container_name: db
    image: postgres

    volumes:
      - ./public/postgres:/var/lib/postgresql/data/pgdata:rw
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - $DB_PORT:5432
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
